# Generated by Django 4.2.16 on 2024-10-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relacionamento",
            old_name="done",
            new_name="ativo",
        ),
        migrations.RemoveField(
            model_name="relacionamento",
            name="description",
        ),
        migrations.AddField(
            model_name="relacionamento",
            name="data_inicio_relacionamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relacionamento",
            name="frase_do_casal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relacionamento",
            name="imagem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relacionamento",
            name="nome_site",
            field=models.CharField(default="", max_length=128, unique=True),
        ),
    ]
